# Generated by Django 4.2.14 on 2024-07-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name': 'Library', 'verbose_name_plural': 'Libraries'},
        ),
        migrations.AlterModelOptions(
            name='preference',
            options={'verbose_name': 'Preference', 'verbose_name_plural': 'Preferences'},
        ),
        migrations.AlterField(
            model_name='library',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='library',
            name='media_type',
            field=models.CharField(choices=[('VID', 'Video'), ('AUD', 'Audio')], max_length=4),
        ),
        migrations.AlterField(
            model_name='preference',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
